FROM python:3.9-slim

# libgl1-mesa-glx    libglib2.0-0  // opencv
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    nano && \
    libgthread-2.0.so.0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
COPY inference.py .
COPY modelo_segmentacao.pth .
COPY main.py .

RUN pip install -r requirements.txt

EXPOSE 8501
