FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt -v

COPY inference.py .
COPY modelo_brain_tumor_classifier.keras .
COPY brain_tumor_dataset ./brain_tumor_dataset